services:
  keep-frontend:
    build:
      dockerfile: docker/Dockerfile.ui
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_AUTH_ENABLED=false
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://keep-backend:8080
    volumes:
      - ./state:/state
    depends_on:
      - backend
  keep-backend:
    build:
      dockerfile: docker/Dockerfile.api
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3
    volumes:
      - ./state:/state
    # command: --multi-tenant
