services:
  frontend:
    build:
      dockerfile: docker/Dockerfile.ui
    ports:
      - '3000:3000'
    env:
      AUTH_ENABLED=false
    volumes:
      - ./state:/state
    depends_on:
      - backend
  backend:
    build:
      dockerfile: docker/Dockerfile.api
    ports:
      - '8080:8080'
    env:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3
    volumes:
      - ./state:/state
