
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: keepuser
      POSTGRES_PASSWORD: keeppassword
      POSTGRES_DB: keepdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keep-frontend:
    extends:
      file: docker-compose.common.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    environment:
      - AUTH_TYPE=NO_AUTH
      - API_URL=http://keep-backend:8080
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    extends:
      file: docker-compose.common.yml
      service: keep-backend-common
    build:
      dockerfile: docker/Dockerfile.dev.api
    environment:
      - AUTH_TYPE=NO_AUTH
      - DATABASE_CONNECTION_STRING=postgresql://keepuser:keeppassword@postgres:5432/keepdb
    volumes:
      - .:/app
      - ./state:/state
    depends_on:
      - postgres

  keep-websocket-server:
    extends:
      file: docker-compose.common.yml
      service: keep-websocket-server-common

volumes:
  postgres_data:
