services:
  keep-frontend:
    extends:
      file: docker-compose.yml
      service: keep-frontend-common
    image: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    ports:
      - "3000:3000"
    environment:
      - AUTH_TYPE=NO_AUTH
    volumes:
      - ./state:/state
    depends_on:
      - keep-backend

  keep-backend:
    image: us-central1-docker.pkg.dev/keephq/keep/keep-api
    ports:
      - "8080:8080"
    environment:
      - AUTH_TYPE=NO_AUTH
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3?check_same_thread=False
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - PUSHER_APP_ID=1
      - PUSHER_APP_KEY=keepappkey
      - PUSHER_APP_SECRET=keepappsecret
      - PUSHER_HOST=keep-websocket-server
      - PUSHER_PORT=6001
    volumes:
      - ./state:/state
  
  keep-websocket-server:
    extends:
      file: common.yml
      service: keep-websocket-server
