services:
  keep-frontend-dev:
    build:
      dockerfile: docker/Dockerfile.dev.ui
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_AUTH_ENABLED=false
      - NEXTAUTH_SECRET=secret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - API_URL=http://keep-backend-dev:8080
    volumes:
      - ./keep-ui:/app
      - /app/node_modules
      - /app/.next
  keep-backend-dev:
    build:
      dockerfile: docker/Dockerfile.dev.api
    ports:
      - '8080:8080'
    environment:
      - PORT=8080
      - SECRET_MANAGER_TYPE=FILE
      - SECRET_MANAGER_DIRECTORY=/state
      - DATABASE_CONNECTION_STRING=sqlite:////state/db.sqlite3
    volumes:
      - ./keep:/code/keep
      - ./state:/state
