version: '3.9'

services:
  mysql:
    image: mysql:latest
    ports:
      - 3366:3306
    restart: unless-stopped
    environment:
      # The user, password and database that Keycloak
      # is going to create and use
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: keycloak_password
      MYSQL_DATABASE: keycloak
      # Self-Explanatory
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - keycloak-and-mysql-volume:/var/lib/mysql
    networks:
      - keycloak-and-mysql-network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    ports:
      - 8181:8080
    restart: unless-stopped
    environment:
      # User and password for the Administration Console
      KEYCLOAK_ADMIN: keep_kc
      KEYCLOAK_ADMIN_PASSWORD: keep_kc
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      # this will be used in keep-realm.json
      KEEP_REALM: keep
      KEEP_ADMIN_USER: keep_admin # default admin user for keep
      KEEP_ADMIN_PASSWORD: keep_admin # default admin password for keep
      KEEP_TENANT_ID: keep #
      KEEP_AUTH_REDICERT_URL: http://localhost:3000/*
      KEEP_CLIENT_ID: keep
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keep-realm.json:/opt/keycloak/data/import/keep-realm.json
      - ./themes:/opt/keycloak/providers
    depends_on:
      - mysql
    networks:
      - keycloak-and-mysql-network

networks:
  keycloak-and-mysql-network:

volumes:
  keycloak-and-mysql-volume:
