services:
  superset:
    image: apache/superset:latest
    container_name: superset
    environment:
      - SUPERSET_LOAD_EXAMPLES=no
      - SUPERSET_WEBSERVER_PORT=8088
      - SUPERSET_CONFIG_PATH=/app/pythonpath/superset_config.py
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py
    command:
      - /bin/sh
      - -c
      - |
        superset db upgrade && \
        superset fab create-admin --username admin --firstname Admin --lastname User --email admin@superset.com --password admin && \
        superset init && \
        superset run -p 8088 --with-threads --reload --debugger
