apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullName }}-pv
spec:
  capacity:
    storage: {{ .Values.database.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/var/lib/mysql"