serviceAccount:
  create: true
  annotations: {}
  name: ""
nameOverride: ""
fullnameOverride: ""

backend:
  enabled: true
  env:
    - name: SECRET_MANAGER_TYPE
      value: FILE
    - name: PORT
      value: "8080"
    - name: SECRET_MANAGER_DIRECTORY
      value: /state
    - name: DATABASE_CONNECTION_STRING
      value: mysql+pymysql://root@keep-database:3306/keep
  openAiApi:
    enabled: false
    openAiApiKey: ""
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/keephq/keep/keep-api
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 8080
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

frontend:
  enabled: true
  env:
    - name: NEXT_PUBLIC_AUTH_ENABLED
      value: "false"
    - name: NEXTAUTH_SECRET
      value: secret
    - name: NEXTAUTH_URL
      value: http://localhost:3000
    - name: API_URL
      value: http://keep-backend:8080
    - name: NEXT_PUBLIC_API_URL
      value: ""
    - name: NEXT_PUBLIC_POSTHOG_KEY
      value: "phc_muk9qE3TfZsX3SZ9XxX52kCGJBclrjhkP9JxAQcm1PZ"
    - name: NEXT_PUBLIC_POSTHOG_HOST
      value: https://app.posthog.com
    - name: ENV
      value: development
    - name: NODE_ENV
      value: development
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/keephq/keep/keep-ui
    pullPolicy: Always
    tag: "latest"
  imagePullSecrets: []
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}

database:
  enabled: true
  replicaCount: 1
  image:
    repository: mysql
    pullPolicy: IfNotPresent
    tag: "latest"
  env:
    - name: MYSQL_ALLOW_EMPTY_PASSWORD
      value: yes
    - name: MYSQL_DATABASE
      value: keep
    - name: MYSQL_PASSWORD
      value: null
  imagePullSecrets: []
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 3306
  resources: {}
  autoscaling:
    enabled: false
  nodeSelector: {}
  tolerations: []
  affinity: {}
