name: Tests
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install Poetry
      uses: snok/install-poetry@v1
    - name: Install dependencies using poetry
      run: poetry install
    - name: Run unit tests and report coverage
      run: poetry run coverage run --branch -m pytest
    - name: Convert coverage results to JSON (for CodeCov support)
      run: poetry run coverage json --omit="keep/providers/*"
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        files: coverage.json
        verbose: true
